export const LOGIN_TO_ACCOUNT = "LOGIN_TO_ACCOUNT";
export const ERROR_LOGIN_ACCOUNT = "ERROR_LOGIN_ACCOUNT";

export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const ERROR_CREATE_ACCOUNT = "ERROR_CREATE_ACCOUNT";

export const GET_TRADER = "GET_TRADER";

export const LOGOUT = "LOGOUT";
export const ERROR_LOGOUT_ACCOUNT = "ERROR_LOGOUT_ACCOUNT";
